### ISSUE TITLE
[BUG] Error ' TypeError: anchor.Wallet is not a constructor' When Trying to Create Storage Account ... lacking dependencies?

### ISSUE THREAD

**Issue by perezsan** [GenesysGo/shdw-drive-bug-reports#2]
**Describe the bug**
Cannot create a storage account with shdw-drive linux x86_64 binary

```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
This is beta software. Use at your own discretion.
/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/helpers/index.js:104
    const wallet = new anchor.Wallet(keypair);
                   ^

TypeError: anchor.Wallet is not a constructor
at getAnchorEnvironmet (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/helpers/index.js:104:20)
at Command.<anonymous> (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:57:73)
at Command.listener [as _actionHandler] (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:481:17)
at /snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1237:65
at Command._chainOrCall (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1153:12)
at Command._parseCommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1237:27)
at Command._dispatchSubcommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1059:25)
at Command._parseCommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1202:19)
at Command.parse (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:890:10)
at Object.<anonymous> (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:1379:21)
```

**To Reproduce**
shdw-drive create-storage-account --keypair {keypair location} --name "{Storage Account Name}" --size 6GB

**Expected behavior**
Expected the creation of an account, but got ziltch.

**Screenshots**
![2022-05-10_03-05-1652178298](https://user-images.githubusercontent.com/857988/167609285-cc03ac50-6cc2-46f6-9220-a0e8c7a961fd.jpg)

**Desktop (please complete the following information):**
 - OS: Funtoo x86_64; Kernel: 5.10.53-gentoo
 - nodeJS ver. 16.15.0 (using nvm)
 
**Additional context**
Also tried running the  'create-storage-account' command with every other nodeJS version I can think of while also installing anchor via 'npm install @project-serum/anchor-cli', but that did not solve the error.

**Comment by perezsan** [comment]
I also tried installing commander via 'npm install commander' but that didn't help, either.

**Comment by robbestad** [comment]
Same with Mac binary

**Comment by tracy-codes** [comment]
@perezsan @robbestad Can you please go to the GitBook, download the latest binary for your system, and report back on if this is happening?

**Comment by perezsan** [comment]
Still boinks....

```
shdw-drive create-storage-account --keypair ~/.config/solana/wallet/id.json --name "testbucket" --size 1GB
```

```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
This is beta software. Use at your own discretion.
/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/helpers/index.js:104
    const wallet = new anchor.Wallet(keypair);
                   ^

TypeError: anchor.Wallet is not a constructor
    at getAnchorEnvironmet (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/helpers/index.js:104:20)
    at Command.<anonymous> (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:59:73)
    at Command.listener [as _actionHandler] (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:481:17)
    at /snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1237:65
    at Command._chainOrCall (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1153:12)
    at Command._parseCommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1237:27)
    at Command._dispatchSubcommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1059:25)
    at Command._parseCommand (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:1202:19)
    at Command.parse (/snapshot/shdw-drive-cli/node_modules/commander/lib/command.js:890:10)
    at Object.<anonymous> (/snapshot/shdw-drive-cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:1405:21)
```

```
~ $ shdw-drive -V
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
This is beta software. Use at your own discretion.
0.0.3
```

**Comment by tracy-codes** [comment]
Awesome, thank you for confirming. I'll check into it, it might be an OS-version specific thing going on. Since I didn't build this on Gentoo, it may be encountering some issues.

We'll try to reproduce the issue based on your specified OS and see what we can uncover.

**Comment by tracy-codes** [comment]
@perezsan This is a fresh Funtoo setup (from https://hub.docker.com/r/funtoo/stage3-generic_64) with only the Solana CLI, shdw-drive v0.0.3 binary, and Nodejs v16.15.0 installed and was not able to reproduce this error.

![image](https://user-images.githubusercontent.com/31976538/167773849-7c621334-8a67-4480-a3ea-91c3556a25c7.png)

I will wait for @robbestad to chime in and see if he can reproduce with the latest Mac binary.

**Comment by perezsan** [comment]
@tracy-codes Interesting ... I am at a loss! Hopefully it's just on my end. For now, I'll just use a container (I'll keep subscribed until it's closed, though.)

**Comment by perezsan** [comment]
Aha! The BROWSER variable in ~/.bashrc was the culprit. Once I commented out the line, and reloaded the terminal, I could create a storage account using the v0.0.3 `shdw-drive` binary. 

Seems like `shdw-drive` does not like the custom BROWSER variable, even when it's set to something vanilla like `export BROWSER=/usr/bin/firefox` so one has to comment it out, or just delete it from the bash environment.

I would suggest if @robbestad is still having problems with the latest Mac x86_64 binary to double-check his ~/.bash_profile for something similarly offending.

**Comment by robbestad** [comment]
I'll check it out in a few hours. The findings sounds very reasonable so I'm almost certain it's the same culprit.

**Comment by robbestad** [comment]
Yes, confirmed. Unsetting the `BROWSER` env fixes the issue, both in the original binary and the latest one.

**Comment by tracy-codes** [comment]
This is terrific information! I'll work to reproduce on my side and then make sure this is handled in the CLI. It looks for an environment variable called "BROWSER" and does different things based on that environment variable. I'll be sure to eliminate that.

I'll follow up once this is resolved.
