### ISSUE TITLE
[BUG]  'upload-multiple-files' option does not work with v0.0.12 ... " TypeError: Cannot read properties of null (reading 'identifier')"

### ISSUE THREAD

**Issue by perezsan** [GenesysGo/shdw-drive-bug-reports#4]
**Describe the bug**
When trying to upload multiple files via CLI, it errors out before being able to select which bucket to upload multiple files to....

```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
This is beta software. Use at your own discretion.
Writing upload logs to /home/user/shdw-drive-upload-16526026486.json.
✔ Collecting all files
/home/user/.nvm/versions/node/v16.15.0/lib/node_modules/@shadow-drive/cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:512
            identifier: account.identifier,
                                ^

TypeError: Cannot read properties of null (reading 'identifier')
    at /home/user/.nvm/versions/node/v16.15.0/lib/node_modules/@shadow-drive/cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:512:33
    at Array.map (<anonymous>)
    at Command.<anonymous> (/home/user/.nvm/versions/node/v16.15.0/lib/node_modules/@shadow-drive/cli/dist/packages/shdw-drive-cli/src/shdw-drive.js:510:38)
```

**To Reproduce**
shdw-drive upload-multiple-files -kp ~/.config/solana/id.json -d folder/

**Expected behavior**
Trying to upload multiple files

OS: Funtoo 1.4 x86_64
nvm/nodeJS 16.15.0

**Additional context**
- All filenames are under 32 byte limit.
- Also tried the same command under a clean lxc funtoo 1.4 container with the same result.

**Comment by perezsan** [comment]
Multiple uploads from CLI appear fixed when tested with v.0.0.24
